import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";

export default function Home() {
  const [date, setDate] = useState(new Date());

  function refreshClock() {
    setDate(new Date());
  }

  useEffect(() => {
    // The setInterval utility calls the given callback function at the specified intervals (in milliseconds).
    const timerId = setInterval(refreshClock, 1000);
    return function cleanup() {
      // clearInterval() in order to cancel the scheduled actions
      clearInterval(timerId);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Clock App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{date.toLocaleTimeString()}</h1>
      </main>
    </div>
  );
}
